version: '1.0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
skip_tags: true
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet publish ./src/Codenizer.HttpClient.Testable/Codenizer.HttpClient.Testable.csproj
  - cmd: dotnet pack ./src/Codenizer.HttpClient.Testable/Codenizer.HttpClient.Testable.csproj
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - cmd: dotnet test ./test/Codenizer.HttpClient.Testable.Tests.Unit/Codenizer.HttpClient.Testable.Tests.Unit.csproj
artifacts:
  - path: '**/*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: ikNyGyovug5pfM++c3HxJQHgaVYHuJeD2U+PUpPeKiV4K1LgFaVtMg1rnbQMJWpq
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
